### ISSUE TITLE
Update to latest Firebrandx palettes

### ISSUE THREAD

**Issue by boktai1000** [dborth/fceugx#352]
FirebrandX has complete restructed his NES palettes to four options now. Thanks to recent efforts as well as the NES Classic being released, it has changed the accuracy of RGB color palettes.

http://www.firebrandx.com/nespalette.html

**Comment by Yamato-san** [comment]
FirebrandX recently finished his work on the NES palettes. There have been massive updates.
There are 4 palettes now:

- "Composite Direct (FBX)" : Unmodified NTSC composite signal capture (recently called "Nostalgia" but renamed due to the misleading name)

- "Original Hardware (FBX)" : This palette is for CRT users. It will trigger the same reactions to the CRT phosphor as a real NTSC NES front-loader does.

- "PVM Style (FBX)" : This palette is for digital display users that want a more authentic CRT experience (as close as can be approximated). It approximates the color and intensity of a Sony PVM CRT screen. 

- "NES-Classic (FBX-FS)" : Updated by measuring the colors with a Color Test Rom (using Hackchi2 hack). More accurate colors than before.

Please see here for more details:
http://www.firebrandx.com/nespalette.html

I would appreciate if FCEUGX could support all of the above palettes. They are the way to go in my opinion!

**Comment by boktai1000** [comment]
I have updated my top comment to reflect that there are now 4 Firebrandx palettes - all of which should be included, whilst removing the old Unsaturated one from the package.

**Comment by Yamato-san** [comment]
Thanks boktai1000

I personally can't wait for this new palette update.

**Comment by boktai1000** [comment]
It appears that Firebrandx has updated his palettes again. I'm still curious on easy it would be to update these, as it seems like it would be as simple as replacing / updating the files included with the application but I guess I'm not entirely sure! Another idea would be to have FCEUGX include a default palette but allow the user to load RGB palettes off SD Card, that way we the user could simply update the palettes or try different palettes as we see fit without having to request an update.

So I guess I would be alright with updating the palettes including, or giving the option for user configurable palettes via SD Card instead (this seems to probably be the best option).

Current Firebrandx palettes via November 2017 zip:

- Composite Direct
- NES Classic
- PC-10
- PVM Style D93
- Smooth
- Sony CXA
- Wavebeam

**Comment by dborth** [comment]
Sounds like a great idea. Someone just has to submit a pull request with the new palletes and I'll do it.
