### ISSUE TITLE
Exit button combo change

### ISSUE THREAD

**Issue by filevans** [dborth/fceugx#419]
Hello please could you make the exit button combo the same as SNES9x gx to have some uniformity across the emulators as they are a completely different set of buttons to exit at the moment and it gets confusing to remember different exit combos
(Even better would be to enable user defined button combo)
Thank you for listening

**Comment by dborth** [comment]
the shared exit for both is the Home button on any Wii controller, including the classic controller. If you're using a Snes controller that has no home button, the combo uses the L and R triggers for that emu

if you're using a Nes controller that has no home button, the combo uses the A and B triggers since the Nes controller didn't have L and R on it.

I guess you're doing something like using an Snes controller on the Nes? I've added an additional combo to match the Snes one.

**Comment by filevans** [comment]
Yes I use a SNES pad for everything

**Comment by Sowden** [comment]
Hey there.  How does the combo for NES controllers with no home button work again?
