### ISSUE TITLE
GC version SD Gecko broken, weird glitch

### ISSUE THREAD

**Issue by 60fpshacksrock** [dborth/fceugx#431]
https://www.imgurupload.com/uploads/20200828/9c060b063f8a73387aa35d470b2bdc0d7ccafaa4.png

Broken since 3.4.6 and even the svn builds after it.

**Comment by dborth** [comment]
Same issue reported here:
https://github.com/dborth/snes9xgx/issues/937

don't know what to tell you, this must be a libogc problem.

**Comment by 60fpshacksrock** [comment]
Okay thanks. Hopefully they can look into it.

**Comment by 60fpshacksrock** [comment]
I forgot to mention it also gives an error about opening the SD.

**Comment by picaron** [comment]
experiencing the same error with fceugx

workaround for now is to use 3.4.3

**Comment by Papy-G** [comment]
This issue is common to the three emulators, it has nothing to do with the way the console is forced to run homebrew (Exploit Under Fire is my main boot method for SWISS), it is due to the program unable to create its own cofiguration file and folder, and it doesn't come in the archive too.

You can copy from one you have that works, as I did from Snes9x to FCEUGX, or you can download them from this link as long as there has been an upload for less than 30 days.

http://dl.free.fr/i3KMJGRBa

I tried for VBAGX later just to check as Emulators can't fulfill my needs so I have plenty of GB/GBA compatible hardware anyways, and it works by copying another's conf file too!

**Comment by dborth** [comment]
that's strange, because the program does indeed try to create the folder and config file. See SavePrefs in preferences.cpp

**Comment by Papy-G** [comment]
What is even more odd is that it can create save files beside it.

What is different in the way it creates the conf file and the saves?

I'm sorry I don't think I may be of any help in high level programming, but i'll try to look where you pointed me just to see if something bugs me.

**Comment by Papy-G** [comment]
bladeoner has found a workaround and applied it on SNES9xGX, might be the path to follow for FCEUGX and VBAGX as well.
