### ISSUE TITLE
Gamecube version hangs up on filebrowser screen again on v3.4.9

### ISSUE THREAD

**Issue by kiwanowski** [dborth/fceugx#439]
the Gamecube version of the app hangs up on boot - on the filebrowser screen. The problem occurs when I try to boot from sd gecko without the sd2sp2.

Maybe it could work when implemented like genesis plus gx - mount sd2sp2 only if you are booting the app from it.

PS: Before merging please check if works with and without the sd2sp2 :)

**Comment by dborth** [comment]
Since I don't own these devices, and don't even have my gamecube set up for homebrew, I haven't been testing myself. I've reached out to others like yourself and haven't gotten much response - so I gave up and released it how it was. I'll post couple test versions here for you to try and if you find one that works good for both sd2sp2 and sd gecko (slot a or slot b) let me know and I'll put that change out.

@bladeoner FYI here's the reason I hadn't mounted sd2sp2 before

**Comment by dborth** [comment]
[fceugx-gc-testb.zip](https://github.com/dborth/fceugx/files/5933760/fceugx-gc-testb.zip)
[fceugx-gc-testa.zip](https://github.com/dborth/fceugx/files/5933762/fceugx-gc-testa.zip)

Can you try these?
-slot a, slot b, sd2sp2 - both inserted, only one inserted
-if you're happy with one or both of those - then also with and without the pref file existing - can it create it?

- does loading games work
- does saving game state work
- does loading/saving prefs work

**Comment by kiwanowski** [comment]
OK so from what I understand, testa prioritizes the SD2SP2 and testb prioritizes the memory card slots. Both of them work with the SDGecko + SD2SP2 and just the SD2SP2. Unfortunately with just the SDGecko I get this screen
![1](https://user-images.githubusercontent.com/10254780/107074403-f840c500-67e8-11eb-9da0-99cf81e16151.jpg)

**Comment by dborth** [comment]
so did sd gecko work before? (ie: in 3.4.8?) has it ever been working?

**Comment by kiwanowski** [comment]
Yes, before 3.4.4 and on 3.4.6-3.4.8

**Comment by kiwanowski** [comment]
OK, so here are my findings: versions 3.4.6-3.4.8 work on the sdgecko only if you first create a settings file using 3.4.3.

**Comment by dborth** [comment]
Okay, thanks that gives me a lot to go on. Here's another test, my hope is:
- sd gecko works OK on port a and b, regardless of whether settings file exists (without sd2sp2 plugged in)
- sd2sp2 works OK, regardless of whether settings file exists (without sdgecko plugged in)
- if both are plugged in, prefs will always be loaded / saved to sd gecko. but otherwise, everything should work OK

[fceugx-gc-test3.zip](https://github.com/dborth/fceugx/files/5937287/fceugx-gc-test3.zip)

**Comment by kiwanowski** [comment]
OK, this one works like it should. I'm glad that you managed to fix it.

**Comment by dborth** [comment]
I'm happy too, thanks for testing.
